<script lang="ts">
	import { theme } from '$lib/stores/theme';
</script>

<button class="theme-toggle" on:click={() => theme.toggle()} aria-label="Toggle dark mode">
	{#if $theme}
		<!-- Generated by IcoMoon.io -->
		<svg
			version="1.1"
			xmlns="http://www.w3.org/2000/svg"
			width="768"
			height="768"
			viewBox="0 0 768 768"
			style="fill: var(--md-sys-color-on-secondary)"
		>
			<g id="icomoon-ignore"> </g>
			<path
				d="M114 594l57-58.5 45 45-57 58.5zM352.5 718.5v-94.5h63v94.5h-63zM384 175.5q79.5 0 135.75 56.25t56.25 135.75-56.25 135.75-135.75 56.25-135.75-56.25-56.25-135.75 56.25-135.75 135.75-56.25zM640.5 336h96v64.5h-96v-64.5zM552 580.5l45-43.5 57 57-45 45zM654 142.5l-57 57-45-45 57-57zM415.5 18v94.5h-63v-94.5h63zM127.5 336v64.5h-96v-64.5h96zM216 154.5l-45 45-57-57 45-45z"
			></path>
		</svg>
	{:else}
		<!-- Generated by IcoMoon.io -->
		<svg
			version="1.1"
			xmlns="http://www.w3.org/2000/svg"
			width="768"
			height="768"
			viewBox="0 0 768 768"
			style="fill: var(--md-sys-color-on-secondary)"
		>
			<g id="icomoon-ignore"> </g>
			<path
				d="M319.5 64.5q133.5 0 227.25 93.75t93.75 225.75-93.75 225.75-227.25 93.75q-87 0-159-42 73.5-42 116.25-116.25t42.75-161.25-42.75-161.25-116.25-116.25q72-42 159-42z"
			></path>
		</svg>
	{/if}
</button>

<style>
	.theme-toggle {
		background: var(--md-sys-color-secondary);
		border: 1px solid var(--md-sys-color-on-secondary);
		border-radius: 50%;
		width: 2.5rem;
		height: 2.5rem;
		display: flex;
		align-items: center;
		justify-content: center;
		cursor: pointer;
		transition: all 0.3s ease;
		box-shadow: var(--shadow-sm);
		display: none;
		> svg {
			width: 1.5rem;
			height: 1.5rem;
		}
	}

	.theme-toggle:hover {
		transform: scale(1.1);
		box-shadow: var(--shadow-md);
	}

	/* .theme-toggle i {
		font-size: 1.25rem;
		color: var(--md-sys-color-on-surface);
	} */
</style>
